### ISSUE TITLE
The OpenXDS - Web application gives build failure

### ISSUE THREAD

**Issue by karkaletsis** [jembi/openxds#6]
[INFO] OpenXDS - Web Application (Struts 2) ............... FAILURE [  1.188 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.673 s
[INFO] Finished at: 2016-02-09T20:58:26+02:00
[INFO] Final Memory: 159M/1039M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-war-plugin:2.0.2:war (default-war) on project openxds-web: Execution default-war of goal org.apache.maven.plugins:maven-war-plugin:2.0.2:war failed: basedir ../target does not exist -> [Help 1]

I tried several changes in pom.xml accroding to basedir param without success. Could you help us?

**Comment by rcrichton** [comment]
Hi, unfortunately I couldn't ever get the webapp to build with the code that we got from the original OpenXDS source. We haven't been using the OpenXDS webapp thus far.

**Comment by karkaletsis** [comment]
Finally I found a way to build it successfully by changing this

<artifactId>maven-war-plugin</artifactId>
from                <version>2.0.2</version>
to                     <version>2.1.1</version>

and 
from                            <directory>../target</directory>
to                            <directory>target</directory>
